// /reset-password — AuthPages (task-009, contracts §C; requirements §8
// "Forgot / Reset Password").
//
// Reached from: the reset link inside the OutboundMessage email
// (`/reset-password?token=…`, generated by task-006 forgot-password flow).

import type { Metadata } from "next";
import { ResetPasswordForm } from "./ResetPasswordForm";

export const metadata: Metadata = { title: "Reset password — MortMortgage" };

export default async function ResetPasswordPage({
  searchParams,
}: {
  searchParams: Promise<{ token?: string }>;
}) {
  const params = await searchParams;
  // Boundary validation: opaque token, non-empty only.
  const token = typeof params.token === "string" && params.token.length > 0 ? params.token : null;
  return (
    <div className="mx-auto flex w-full max-w-md flex-col px-4 py-12 sm:py-16">
      <ResetPasswordForm token={token} />
    </div>
  );
}
