// /verify-email — AuthPages (task-009, contracts §C; requirements §8 "Verify Email").
//
// Reached from: the verification link inside the OutboundMessage email
// (`/verify-email?token=…`, generated by task-006); sign-in when
// SignInResponse.status = "verification-pending" (no token — pending view with
// the resend action); /sign-up success screen explanation.

import type { Metadata } from "next";
import { VerifyEmailClient } from "./VerifyEmailClient";
import { safeRedirect } from "@/components/auth/redirect";

export const metadata: Metadata = { title: "Verify email — MortMortgage" };

export default async function VerifyEmailPage({
  searchParams,
}: {
  searchParams: Promise<{ token?: string; redirectTo?: string }>;
}) {
  const params = await searchParams;
  // Boundary validation: token is an opaque string — pass through non-empty only.
  const token = typeof params.token === "string" && params.token.length > 0 ? params.token : null;
  const redirectTo = safeRedirect(params.redirectTo ?? null);
  return (
    <div className="mx-auto flex w-full max-w-md flex-col px-4 py-12 sm:py-16">
      <VerifyEmailClient token={token} redirectTo={redirectTo} />
    </div>
  );
}
