-- task-004: seed every requirements §4.6.11 SystemConfig setting with its stated
-- default (generated from CONFIG_REGISTRY in src/lib/services/config.ts — the
-- single key authority). Values are JSONB. Idempotent: ON CONFLICT (key) DO NOTHING,
-- so replaying the migration never duplicates rows or overwrites operator changes.
INSERT INTO "SystemConfig" ("id", "key", "value", "description", "updatedAt")
VALUES
  (gen_random_uuid()::text, 'escalation.ltvThresholdPercent', '80'::jsonb, 'LTV above which an application escalates to two-level review (§4.6.11 default 80%).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'escalation.dtiThresholdPercent', '43'::jsonb, 'DTI above which an application escalates to two-level review (§4.6.11 default 43%).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ltv.submissionBlockPercent', '97'::jsonb, 'LTV at or above which submission is blocked (§4.6.11 default 97%).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ltv.warningPercent', '80'::jsonb, 'LTV above which the wizard shows a warning (§4.6.11 default 80%).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'dti.warningPercent', '43'::jsonb, 'DTI above which the wizard shows a warning (§4.6.11 default 43%).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'approval.twoLevelLoanTypes', '["fha","va","usda"]'::jsonb, 'Loan types that always require Level-1 + Level-2 approval (§4.6.11 default FHA, VA, USDA).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'sla.businessDays.application_received', '2'::jsonb, 'Business-day SLA for the Application Received state (§4.4.1 default 2).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'sla.businessDays.completeness_validated', '3'::jsonb, 'Business-day SLA for the Completeness Validated state (§4.4.1 default 3).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'sla.businessDays.documents_received', '2'::jsonb, 'Business-day SLA for the Supporting Documents Received state (§4.4.1 default 2).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'sla.businessDays.aus_executed', '2'::jsonb, 'Business-day SLA for the AUS Executed state (§4.4.1 default 2).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'sla.businessDays.preliminary_decision', '2'::jsonb, 'Business-day SLA for the Preliminary Decision state (§4.4.1 default 2).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'sla.businessDays.escalated_review', '2'::jsonb, 'Business-day SLA for the Escalated Review state (§4.4.1 default 2).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'sla.businessDays.conditional_approval', '10'::jsonb, 'Business-day SLA for the Conditional Approval state (§4.4.1 default 10).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'sla.businessDays.revision_requested', '10'::jsonb, 'Business-day SLA for the Revision Requested state — borrower clock (§4.4.1 default 10).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'sla.overallDecisionCalendarDays', '30'::jsonb, 'Calendar days from submission to final decision tracked on the detail page (§4.6.11 default 30).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'workload.capacityYellow', '9'::jsonb, 'Active-assignment count at which a caseworker shows yellow capacity (§4.6.11 default 9).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'workload.capacityRed', '13'::jsonb, 'Active-assignment count at which a caseworker shows red capacity (§4.6.11 default 13).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'autoAssign.productivityAware', 'false'::jsonb, 'Whether auto-assignment weighs caseworker productivity (§4.6.11 default off).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'autoAssign.productivityWeight', '0.25'::jsonb, 'Weight of productivity in auto-assignment scoring, 0–1 (§4.6.11 default 0.25).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'application.staleCopyThresholdDays', '90'::jsonb, 'Age in days beyond which a copy-source application triggers the staleness advisory (§4.6.11 default 90).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'documents.maxFileSizeMb', '10'::jsonb, 'Maximum uploaded document size in megabytes (§4.6.11 default 10, INV-024).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'documents.maxPerApplication', '25'::jsonb, 'Maximum number of documents per application (§4.6.11 default 25, INV-024).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'notes.maxLength', '4000'::jsonb, 'Maximum characters for internal/formal notes (§4.6.11 default 4,000, INV-024).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'chatter.maxLength', '1000'::jsonb, 'Maximum characters per chatter message (§4.6.11 default 1,000, INV-024).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ocr.retryLimit', '5'::jsonb, 'Maximum automatic OCR retry attempts per document job (§4.6.11 default 5, INV-024).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'session.idleTimeoutMinutes', '30'::jsonb, 'Idle minutes after which a session expires (§4.6.11 default 30).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'session.absoluteTimeoutHours', '12'::jsonb, 'Absolute session lifetime in hours regardless of activity (§4.6.11 default 12).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'password.expiryDays', '180'::jsonb, 'Days before a password expires and must be changed (§4.6.11 default 180).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'password.historyDepth', '5'::jsonb, 'Number of prior passwords that may not be reused (§4.6.11 default 5).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'password.lockoutAttempts', '5'::jsonb, 'Failed sign-in attempts before temporary lockout (§4.6.11 default 5).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'password.lockoutMinutes', '15'::jsonb, 'Minutes an account stays locked after too many failed attempts (§4.6.11 default 15).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'rateLimit.authAttempts', '10'::jsonb, 'Allowed attempts per window per key (account/IP) for authentication endpoints (§4.1.9 default 10).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'rateLimit.authWindowMinutes', '15'::jsonb, 'Window length in minutes for the authentication-endpoint rate limit (§4.1.9 default 15).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'rateLimit.generalPerMinute', '60'::jsonb, 'Allowed requests per minute per key for non-auth rate-limited endpoints (§4.1.9 default 60).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'pagination.maxPageSize', '100'::jsonb, 'Server-enforced maximum page size for every list endpoint (§4.6.11 default 100, INV-036).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'audit.exportRowCap', '100000'::jsonb, 'Maximum rows per audit-log CSV export (§4.6.11 default 100,000, INV-024).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'hmda.lei', '""'::jsonb, '20-character Legal Entity Identifier for HMDA LAR export (§4.6.11 default blank — LAR export blocks until set).', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'hmda.agencyCode', '""'::jsonb, 'Single-digit HMDA agency code for LAR export (§4.6.11 default blank — LAR export blocks until set).', CURRENT_TIMESTAMP)
ON CONFLICT ("key") DO NOTHING;
