// HMDA LAR export service (task-042 — REQ-076 / DATA-003 / NFR-015, RFP
// §4.9.4 / §5.3, ASM-003 / ASM-005 / ASM-010, WALK-005, SEC-14, INV-037).
//
// Produces the FFIEC pipe-delimited LAR file for a Supervisor-selected
// calendar year: one transmittal-sheet header record (record id 1) + one LAR
// record (record id 2, 110 fields) per application with a reportable action
// in the year. The field order and every code table live in
// hmda-lar-mapping.ts (the ASM-010 machine-readable mapping — this builder
// and the evidence suite both read it).
//
// SEC-14 / WALK-005: records are generated by STREAMING QUERY — a keyset
// cursor over Application (batches <= 1000) with per-batch bounded loads for
// checks and denial records; the full set is never held in memory. Every
// SELECT issued here carries a LIMIT (take) or is an aggregate COUNT — this
// is query-log verified by the evidence suite.
//
// Reportable membership + action mapping (ASM-005 / AC-50, documented):
//   - approved, borrower_notified+outcome=approved  -> 2 (approved but not
//     accepted; loans are never originated in-system), action date decidedAt
//   - declined_by_borrower                          -> 2 (ASM-005), action
//     date stateEnteredAt (the borrower's decline moment)
//   - denied, borrower_notified+outcome=denied      -> 3, action date decidedAt
//   - withdrawn                                     -> 4, action date
//     stateEnteredAt (the withdrawal moment; no decision exists)
//   - every other state is IN-FLIGHT and EXCLUDED; "file closed for
//     incompleteness" (5) is unused (no closure mechanism exists).
// Calendar-year membership is evaluated on the action date in the CONFIGURED
// company time zone (INV-045, `company.timeZone`, default America/New_York):
// the year window is
// [Jan 1 00:00 local, next Jan 1 00:00 local), computed from the zone's real
// UTC offset at each boundary (never a hardcoded offset).
//
// INV-037 (pipe-delimiter survival): free-text values (street, city,
// ethnicity/race free-forms, denial free-form) are sanitized by replacing the
// field delimiter "|" with "/" and CR/LF with spaces — the value survives
// legibly and the file stays field-aligned. Documented here and in the
// mapping artifact.

import type { PrismaClient, Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { ERROR_CODES, HttpProblem } from "@/lib/http/errors";
import { getStringSetting } from "@/lib/services/config";
import { getCompanyTimeZone } from "@/lib/services/sla";
import { decryptField } from "@/lib/crypto/encryption";
import { buildQualificationInput } from "@/lib/services/qualification";
import { monthlyIncomeCents } from "@/lib/pure/qualification";
import { simulatePricing, PricingInputError, type PricingInput } from "@/lib/pure/simulations/pricing";
import type { AusRecommendation } from "@/lib/pure/simulations/check-results";
import {
  HMDA_ACTION_TAKEN,
  HMDA_AUS_RESULT,
  HMDA_DENIAL_REASON,
  HMDA_ETHNICITY,
  HMDA_LOAN_PURPOSE,
  HMDA_LOAN_TYPE,
  HMDA_MANUFACTURED_HOME,
  HMDA_MANUFACTURED_HOME_UNCAPTURED,
  HMDA_NOT_MANUFACTURED_HOME,
  HMDA_OCCUPANCY,
  HMDA_RACE,
  HMDA_SEX,
  LAR_FIELD_COUNT,
  NO_CO_APPLICANT,
  TS_FIELD_COUNT,
  type ManufacturedHomeFields,
  type ManufacturedHomeLandInterest,
} from "@/lib/services/exports/hmda-lar-mapping";

// ---------------------------------------------------------------------------
// Query-parameter boundary (contracts §B: `?year=YYYY` REQUIRED)
// ---------------------------------------------------------------------------

/** Validate and parse `?year=YYYY`. Throws HttpProblem 400 with details[]. */
export function parseLarYear(request: Request): number {
  const url = new URL(request.url);
  const raw = url.searchParams.get("year");
  const details: string[] = [];
  if (raw === null || raw.trim() === "") {
    details.push("year: required — a four-digit calendar year (?year=YYYY)");
  } else if (!/^\d{4}$/.test(raw.trim())) {
    details.push("year: must be a four-digit calendar year (YYYY)");
  } else {
    const year = Number(raw.trim());
    if (year < 1900 || year > 2199) {
      details.push("year: must be a plausible calendar year (1900-2199)");
    } else {
      return year;
    }
  }
  throw new HttpProblem(400, ERROR_CODES.validationError, "Request validation failed", {
    details,
  });
}

// ---------------------------------------------------------------------------
// Config gate (contracts §B: 409 until HMDA LEI + agency code are configured)
// ---------------------------------------------------------------------------

export interface HmdaLarConfig {
  lei: string;
  agencyCode: string;
  /** Company IANA zone resolved at call time (INV-045) — year window + dates. */
  timeZone: string;
}

/**
 * Read hmda.lei + hmda.agencyCode via the config service (never hardcoded).
 * Throws HttpProblem 409 while EITHER is blank (§4.6.11 defaults are blank).
 */
export async function requireHmdaConfig(): Promise<HmdaLarConfig> {
  const [lei, agencyCode, timeZone] = await Promise.all([
    getStringSetting("hmda.lei"),
    getStringSetting("hmda.agencyCode"),
    getCompanyTimeZone(),
  ]);
  const missing: string[] = [];
  if (lei.trim() === "") missing.push("HMDA LEI (hmda.lei)");
  if (agencyCode.trim() === "") missing.push("HMDA agency code (hmda.agencyCode)");
  if (missing.length > 0) {
    throw new HttpProblem(
      409,
      ERROR_CODES.conflict,
      `HMDA LAR export is blocked until the following configuration is set: ${missing.join(", ")}`,
    );
  }
  return { lei: lei.trim(), agencyCode: agencyCode.trim(), timeZone };
}

// ---------------------------------------------------------------------------
// Calendar-year window (configured company zone — INV-045)
// ---------------------------------------------------------------------------

const PARTS_FORMATS = new Map<string, Intl.DateTimeFormat>();

function partsFormat(timeZone: string): Intl.DateTimeFormat {
  let fmt = PARTS_FORMATS.get(timeZone);
  if (!fmt) {
    fmt = new Intl.DateTimeFormat("en-US", {
      timeZone,
      hourCycle: "h23",
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
    });
    PARTS_FORMATS.set(timeZone, fmt);
  }
  return fmt;
}

function zoneParts(instant: Date, timeZone: string): Record<string, number> {
  const out: Record<string, number> = {};
  for (const part of partsFormat(timeZone).formatToParts(instant)) {
    if (part.type !== "literal") out[part.type] = Number(part.value);
  }
  return out;
}

/** The zone's UTC offset (ms) at a given instant. */
function zoneOffsetMs(instant: Date, timeZone: string): number {
  const p = zoneParts(instant, timeZone);
  const asIfUtc = Date.UTC(p.year!, p.month! - 1, p.day!, p.hour!, p.minute!, p.second!);
  return asIfUtc - Math.floor(instant.getTime() / 1000) * 1000;
}

/** UTC instant of local midnight on Jan 1 of `year` in `timeZone` (two-pass, DST-safe). */
function zonedYearStartUtc(year: number, timeZone: string): Date {
  const naive = Date.UTC(year, 0, 1, 0, 0, 0);
  const first = new Date(naive - zoneOffsetMs(new Date(naive), timeZone));
  return new Date(naive - zoneOffsetMs(first, timeZone));
}

/** UTC instants of [Jan 1 00:00 local, next Jan 1 00:00 local) in the company zone. */
export function larYearWindowUtc(year: number, timeZone: string): { start: Date; end: Date } {
  return {
    start: zonedYearStartUtc(year, timeZone),
    end: zonedYearStartUtc(year + 1, timeZone),
  };
}

/** Calendar-date parts of an instant in the company time zone. */
export function etDateParts(
  instant: Date,
  timeZone: string,
): { year: number; month: number; day: number } {
  const p = zoneParts(instant, timeZone);
  return { year: p.year!, month: p.month!, day: p.day! };
}

/** YYYYMMDD (company time zone) for the LAR date fields. */
function larDate(instant: Date | null, timeZone: string): string {
  if (!instant) return "NA";
  const { year, month, day } = etDateParts(instant, timeZone);
  return `${year}${String(month).padStart(2, "0")}${String(day).padStart(2, "0")}`;
}

// ---------------------------------------------------------------------------
// ULI (LEI + applicationNumber + ISO 7064 MOD 97-10 check digits)
// ---------------------------------------------------------------------------

/** MOD 97 of the base-10 expansion where A=10..Z=35 (ISO/IEC 7064 mapping). */
export function uliMod97(value: string): number {
  let rem = 0;
  for (const ch of value.toUpperCase()) {
    let mapped: number;
    if (ch >= "0" && ch <= "9") mapped = ch.charCodeAt(0) - 48;
    else if (ch >= "A" && ch <= "Z") mapped = ch.charCodeAt(0) - 55; // A=10..Z=35
    else throw new Error(`ULI characters must be alphanumeric, got "${ch}"`);
    rem = (rem * (mapped > 9 ? 100 : 10) + mapped) % 97;
  }
  return rem;
}

/** Two check digits per ISO/IEC 7064 MOD 97-10 (98 - mod97(base + "00")). */
export function uliCheckDigits(base: string): string {
  const rem = uliMod97(`${base}00`);
  return String(98 - rem).padStart(2, "0");
}

/**
 * ULI = LEI + applicationNumber (non-alphanumerics stripped: MM-YYYY-NNNNNN
 * becomes MMYYYYNNNNNN) + 2 check digits. A valid ULI satisfies mod97 == 1.
 */
export function buildUli(lei: string, applicationNumber: string): string {
  const loanId = applicationNumber.replace(/[^0-9A-Za-z]/g, "").toUpperCase();
  const base = `${lei.toUpperCase()}${loanId}`;
  return `${base}${uliCheckDigits(base)}`;
}

// ---------------------------------------------------------------------------
// Age at application date (REQ-076: never the export date)
// ---------------------------------------------------------------------------

/**
 * Whole years completed between an ISO DOB (YYYY-MM-DD) and an application
 * calendar date. Standard (month, day) comparison: a Feb-29 birthday is not
 * yet complete on Feb 28 of a non-leap year and IS complete on Mar 1 — the
 * documented Feb-29 convention (INV-037).
 */
export function ageAtDate(
  dobIso: string,
  onDate: { year: number; month: number; day: number },
): number | null {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(dobIso.trim());
  if (!m) return null;
  const dobYear = Number(m[1]);
  const dobMonth = Number(m[2]);
  const dobDay = Number(m[3]);
  let age = onDate.year - dobYear;
  if (onDate.month < dobMonth || (onDate.month === dobMonth && onDate.day < dobDay)) {
    age -= 1;
  }
  return age;
}

// ---------------------------------------------------------------------------
// Reportable-set query (WALK-005)
// ---------------------------------------------------------------------------

function reportableWhere(year: number, timeZone: string): Prisma.ApplicationWhereInput {
  const { start, end } = larYearWindowUtc(year, timeZone);
  return {
    OR: [
      {
        workflowState: { in: ["approved", "denied", "borrower_notified"] },
        decidedAt: { gte: start, lt: end },
      },
      {
        workflowState: { in: ["withdrawn", "declined_by_borrower"] },
        stateEnteredAt: { gte: start, lt: end },
      },
    ],
  };
}

/** Aggregate COUNT of reportable applications (transmittal-sheet field 13). */
export async function countReportableApplications(
  year: number,
  db: PrismaClient = prisma,
): Promise<number> {
  // INV-045: the year window depends on the configured zone, resolved here.
  return db.application.count({ where: reportableWhere(year, await getCompanyTimeZone()) });
}

// ---------------------------------------------------------------------------
// Value helpers
// ---------------------------------------------------------------------------

/** INV-037: free text survives, the file stays field-aligned. */
export function sanitizeLarText(value: string): string {
  return value.replace(/\|/g, "/").replace(/[\r\n]+/g, " ").trim();
}

function asObject(value: unknown): Record<string, unknown> | null {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return null;
  return value as Record<string, unknown>;
}

function str(value: unknown): string | null {
  return typeof value === "string" && value.trim() !== "" ? value : null;
}

function num(value: unknown): number | null {
  return typeof value === "number" && Number.isFinite(value) ? value : null;
}

function strArray(value: unknown): string[] {
  return Array.isArray(value) ? value.filter((v): v is string => typeof v === "string") : [];
}

function decimalToNumber(value: Prisma.Decimal | null): number | null {
  return value === null ? null : Number(value);
}

// ---------------------------------------------------------------------------
// Demographic field groups
// ---------------------------------------------------------------------------

interface DemographicFields {
  codes: [string, string, string, string, string];
  freeForm: string;
  visualObservation: string;
}

function fiveSlots(mapped: string[]): [string, string, string, string, string] {
  return [mapped[0] ?? "", mapped[1] ?? "", mapped[2] ?? "", mapped[3] ?? "", mapped[4] ?? ""];
}

/**
 * Visual-observation code (DATA-003: electronic collection, never visual
 * observation): 2 when the applicant provided the value, 3 when not provided.
 */
function visualObs(provided: boolean): string {
  return provided ? "2" : "3";
}

function ethnicityFields(demo: Record<string, unknown> | null, coApplicant: boolean, exists: boolean): DemographicFields {
  if (coApplicant && !exists) {
    return { codes: [NO_CO_APPLICANT.ethnicity, "", "", "", ""], freeForm: "", visualObservation: NO_CO_APPLICANT.visualObservation };
  }
  const values = strArray(demo?.ethnicity).map((v) => HMDA_ETHNICITY[v]).filter((c): c is string => c !== undefined);
  const provided = values.some((c) => c !== "3");
  if (values.length === 0) {
    return { codes: ["3", "", "", "", ""], freeForm: "", visualObservation: "3" };
  }
  const freeForm = str(demo?.ethnicityOtherDetail);
  return {
    codes: fiveSlots(values),
    freeForm: freeForm ? sanitizeLarText(freeForm) : "",
    visualObservation: visualObs(provided),
  };
}

interface RaceFields {
  codes: [string, string, string, string, string];
  tribeFreeForm: string;
  otherAsianFreeForm: string;
  otherPacificFreeForm: string;
  visualObservation: string;
}

function raceFields(demo: Record<string, unknown> | null, coApplicant: boolean, exists: boolean): RaceFields {
  if (coApplicant && !exists) {
    return { codes: [NO_CO_APPLICANT.race, "", "", "", ""], tribeFreeForm: "", otherAsianFreeForm: "", otherPacificFreeForm: "", visualObservation: NO_CO_APPLICANT.visualObservation };
  }
  const raw = strArray(demo?.race);
  const values = raw.map((v) => HMDA_RACE[v]).filter((c): c is string => c !== undefined);
  if (values.length === 0) {
    return { codes: ["6", "", "", "", ""], tribeFreeForm: "", otherAsianFreeForm: "", otherPacificFreeForm: "", visualObservation: "3" };
  }
  const provided = values.some((c) => c !== "6");
  // raceOtherDetails entries are assigned, in order, to the free-form slots
  // whose parent codes are selected (tribe <- 1, other Asian <- 27, other
  // Pacific Islander <- 44) — documented in the mapping artifact.
  const details = strArray(demo?.raceOtherDetails).map(sanitizeLarText);
  let detailIndex = 0;
  const takeDetail = (selected: boolean): string =>
    selected && detailIndex < details.length ? details[detailIndex++]! : "";
  const tribeFreeForm = takeDetail(values.includes("1"));
  const otherAsianFreeForm = takeDetail(values.includes("27"));
  const otherPacificFreeForm = takeDetail(values.includes("44"));
  return { codes: fiveSlots(values), tribeFreeForm, otherAsianFreeForm, otherPacificFreeForm, visualObservation: visualObs(provided) };
}

function sexFields(demo: Record<string, unknown> | null, coApplicant: boolean, exists: boolean): { code: string; visualObservation: string } {
  if (coApplicant && !exists) {
    return { code: NO_CO_APPLICANT.sex, visualObservation: NO_CO_APPLICANT.visualObservation };
  }
  const value = str(demo?.sex);
  const code = value ? HMDA_SEX[value] ?? "3" : "3";
  return { code, visualObservation: visualObs(code === "1" || code === "2") };
}

// ---------------------------------------------------------------------------
// Streaming file generation
// ---------------------------------------------------------------------------

/** Default WALK-005 batch size (contracts: batches <= 1000). */
const DEFAULT_BATCH_SIZE = 1000;

export interface LarStreamOptions {
  /** Cursor batch size (<= 1000; overridable for evidence). */
  batchSize?: number;
}

const LAR_APP_SELECT = {
  id: true,
  applicationNumber: true,
  workflowState: true,
  outcome: true,
  submittedAt: true,
  decidedAt: true,
  stateEnteredAt: true,
  dti: true,
  cltv: true,
  ltv: true,
  data: {
    select: {
      loan: true,
      subjectProperty: true,
      liabilities: true,
      otherLiabilities: true,
      realEstateOwned: true,
      proposedHousingExpense: true,
    },
  },
} satisfies Prisma.ApplicationSelect;

type LarAppRow = Prisma.ApplicationGetPayload<{ select: typeof LAR_APP_SELECT }>;

interface BorrowerRow {
  id: string;
  applicationId: string;
  ordinal: number;
  dateOfBirthCiphertext: Uint8Array | null;
  dateOfBirthKeyId: string | null;
  demographics: Prisma.JsonValue | null;
  employments: Prisma.JsonValue | null;
  otherIncome: Prisma.JsonValue | null;
}

interface CheckRow {
  applicationId: string;
  checkType: string;
  isStale: boolean;
  completedAt: Date | null;
  result: Prisma.JsonValue | null;
}

interface DenialRow {
  applicationId: string;
  denialReasons: string[];
  denialReasonOtherText: string | null;
  createdAt: Date;
}

/**
 * Bounded per-batch load of a related table: keyset cursor on id with the
 * batch size as LIMIT so every emitted SELECT is cursor/LIMIT-bounded
 * (SEC-14 evidence checks the query log).
 */
async function loadAllBatched<T extends { id: string }>(
  fetchPage: (cursorId: string | null) => Promise<T[]>,
): Promise<T[]> {
  const rows: T[] = [];
  let cursorId: string | null = null;
  for (;;) {
    const page = await fetchPage(cursorId);
    rows.push(...page);
    if (page.length === 0) break;
    cursorId = page[page.length - 1]!.id;
  }
  return rows;
}

/**
 * Generate the complete pipe-delimited LAR file as an async stream of lines
 * (each terminated with "\n"): transmittal-sheet header first, then one
 * 110-field record per reportable application, streamed by keyset cursor.
 */
export async function* generateLarFile(
  year: number,
  cfg: HmdaLarConfig,
  db: PrismaClient = prisma,
  opts: LarStreamOptions = {},
): AsyncGenerator<string> {
  const batchSize = Math.max(1, Math.min(opts.batchSize ?? DEFAULT_BATCH_SIZE, 1000));
  const where = reportableWhere(year, cfg.timeZone);

  // Transmittal sheet (15 fields — hmda-lar-mapping.ts TS_FIELDS).
  const total = await db.application.count({ where });
  const tsFields = [
    "1",
    "MortMortgage",
    String(year),
    "4",
    "NA",
    "NA",
    "NA",
    "NA",
    "NA",
    "NA",
    "NA",
    cfg.agencyCode,
    String(total),
    "NA",
    cfg.lei,
  ];
  if (tsFields.length !== TS_FIELD_COUNT) {
    throw new Error(`transmittal sheet produced ${tsFields.length} fields, expected ${TS_FIELD_COUNT}`);
  }
  yield `${tsFields.join("|")}\n`;

  let cursorId: string | null = null;
  for (;;) {
    const apps: LarAppRow[] = await db.application.findMany({
      where,
      orderBy: { id: "asc" },
      take: batchSize,
      cursor: cursorId === null ? undefined : { id: cursorId },
      skip: cursorId === null ? 0 : 1,
      select: LAR_APP_SELECT,
    });
    if (apps.length === 0) break;
    cursorId = apps[apps.length - 1]!.id;
    const ids = apps.map((a) => a.id);

    // Borrower rows for the batch (own LIMITed cursor pages — SEC-14; at
    // most 2 per application, INV-035).
    const borrowerRows: BorrowerRow[] = await loadAllBatched((cur) =>
      db.borrower.findMany({
        where: { applicationId: { in: ids } },
        orderBy: { id: "asc" },
        take: batchSize,
        cursor: cur === null ? undefined : { id: cur },
        skip: cur === null ? 0 : 1,
        select: {
          id: true,
          applicationId: true,
          ordinal: true,
          dateOfBirthCiphertext: true,
          dateOfBirthKeyId: true,
          demographics: true,
          employments: true,
          otherIncome: true,
        },
      }),
    );
    const borrowersByApp = new Map<string, BorrowerRow[]>();
    for (const row of borrowerRows) {
      const list = borrowersByApp.get(row.applicationId) ?? [];
      list.push(row);
      borrowersByApp.set(row.applicationId, list);
    }
    for (const list of borrowersByApp.values()) list.sort((a, b) => a.ordinal - b.ordinal);

    // Latest completed non-superseded credit / aus / avm per application.
    const checkRows = await loadAllBatched((cur) =>
      db.underwritingResult.findMany({
        where: {
          applicationId: { in: ids },
          checkType: { in: ["credit", "aus", "avm"] },
          status: "completed",
          supersededById: null,
        },
        orderBy: { id: "asc" },
        take: batchSize,
        ...(cur ? { cursor: { id: cur }, skip: 1 } : {}),
        select: {
          id: true,
          applicationId: true,
          checkType: true,
          isStale: true,
          completedAt: true,
          result: true,
        },
      }),
    );
    // Deny approval records (denial reasons, WF-024/VR-087).
    const denialRows = await loadAllBatched((cur) =>
      db.approvalRecord.findMany({
        where: { applicationId: { in: ids }, decision: "deny" },
        orderBy: { id: "asc" },
        take: batchSize,
        ...(cur ? { cursor: { id: cur }, skip: 1 } : {}),
        select: {
          id: true,
          applicationId: true,
          denialReasons: true,
          denialReasonOtherText: true,
          createdAt: true,
        },
      }),
    );

    const latestCheck = new Map<string, CheckRow>();
    for (const row of checkRows) {
      const key = `${row.applicationId}:${row.checkType}`;
      const prev = latestCheck.get(key);
      if (!prev || (row.completedAt?.getTime() ?? 0) > (prev.completedAt?.getTime() ?? 0)) {
        latestCheck.set(key, row);
      }
    }
    const latestDenial = new Map<string, DenialRow>();
    for (const row of denialRows) {
      const prev = latestDenial.get(row.applicationId);
      if (!prev || row.createdAt.getTime() > prev.createdAt.getTime()) {
        latestDenial.set(row.applicationId, row);
      }
    }

    for (const app of apps) {
      const fields = buildLarRecord(
        app,
        borrowersByApp.get(app.id) ?? [],
        cfg,
        latestCheck.get(`${app.id}:credit`) ?? null,
        latestCheck.get(`${app.id}:aus`) ?? null,
        latestCheck.get(`${app.id}:avm`) ?? null,
        latestDenial.get(app.id) ?? null,
      );
      if (fields.length !== LAR_FIELD_COUNT) {
        throw new Error(`LAR record produced ${fields.length} fields, expected ${LAR_FIELD_COUNT}`);
      }
      yield `${fields.join("|")}\n`;
    }
  }
}

// ---------------------------------------------------------------------------
// One LAR record (field order authority: hmda-lar-mapping.ts LAR_FIELDS)
// ---------------------------------------------------------------------------

function actionTakenFor(app: LarAppRow): { code: string; date: Date | null } {
  switch (app.workflowState) {
    case "withdrawn":
      return { code: HMDA_ACTION_TAKEN.withdrawn, date: app.stateEnteredAt };
    case "declined_by_borrower":
      return { code: HMDA_ACTION_TAKEN.approvedButNotAccepted, date: app.stateEnteredAt };
    case "denied":
      return { code: HMDA_ACTION_TAKEN.denied, date: app.decidedAt ?? app.stateEnteredAt };
    case "approved":
      return { code: HMDA_ACTION_TAKEN.approvedButNotAccepted, date: app.decidedAt ?? app.stateEnteredAt };
    case "borrower_notified":
      return app.outcome === "denied"
        ? { code: HMDA_ACTION_TAKEN.denied, date: app.decidedAt }
        : { code: HMDA_ACTION_TAKEN.approvedButNotAccepted, date: app.decidedAt };
    default:
      // Unreachable: reportableWhere admits only the five states above.
      throw new Error(`non-reportable state reached the LAR builder: ${app.workflowState}`);
  }
}

/**
 * LAR fields 89 (Manufactured Home Secured Property Type) + 90 (Manufactured
 * Home Land Property Interest), derived TOGETHER from the VR-135 capture.
 *
 * Site-built collateral reports 89 = 3 (Not applicable) / 90 = 5 (Not
 * applicable) — 90 = 5 is the FFIEC value for a loan NOT secured by a
 * manufactured home, so it is legal only here.
 *
 * A manufactured home with no captured (or a self-contradictory
 * "not-applicable") land interest falls to the documented default in
 * HMDA_MANUFACTURED_HOME_UNCAPTURED; see that constant for the justification.
 */
export function manufacturedHomeCodes(
  manufactured: boolean,
  landInterest: string | null,
): ManufacturedHomeFields {
  if (!manufactured) return HMDA_NOT_MANUFACTURED_HOME;
  // The membership guard keeps the lookup honest: HMDA_MANUFACTURED_HOME is
  // keyed by the contract's ManufacturedHomeLandInterest enum, so an unexpected
  // literal falls to the documented default rather than indexing with `any`.
  const mapped =
    landInterest !== null && landInterest in HMDA_MANUFACTURED_HOME
      ? HMDA_MANUFACTURED_HOME[landInterest as ManufacturedHomeLandInterest]
      : undefined;
  return mapped ?? HMDA_MANUFACTURED_HOME_UNCAPTURED;
}

function decryptDob(row: BorrowerRow): string | null {
  if (!row.dateOfBirthCiphertext || !row.dateOfBirthKeyId) return null;
  try {
    return decryptField({
      ciphertext: Buffer.from(row.dateOfBirthCiphertext),
      keyId: row.dateOfBirthKeyId,
    });
  } catch {
    return null;
  }
}

function buildLarRecord(
  app: LarAppRow,
  borrowers: BorrowerRow[],
  cfg: HmdaLarConfig,
  credit: CheckRow | null,
  aus: CheckRow | null,
  avm: CheckRow | null,
  denial: DenialRow | null,
): string[] {
  const loan = asObject(app.data?.loan ?? null);
  const subjectProperty = asObject(app.data?.subjectProperty ?? null);
  const address = asObject(subjectProperty?.address);
  const geocode = asObject(subjectProperty?.geocode);
  const proposedHousingExpense = asObject(app.data?.proposedHousingExpense ?? null);

  const primary = borrowers.find((b) => b.ordinal === 1) ?? null;
  const coBorrower = borrowers.find((b) => b.ordinal === 2) ?? null;
  const primaryDemo = asObject(primary?.demographics ?? null);
  const coDemo = asObject(coBorrower?.demographics ?? null);

  const action = actionTakenFor(app);
  const isApprovedNotAccepted = action.code === HMDA_ACTION_TAKEN.approvedButNotAccepted;

  // --- Construction method / units --------------------------------------
  const propertyType = str(subjectProperty?.propertyType);
  const manufactured = propertyType === "manufactured-home" || subjectProperty?.manufacturedHome === true;
  const constructionMethod = manufactured ? "2" : "1";
  // VR-135 / CH-011: fields 89 + 90 are derived TOGETHER from the captured
  // SubjectProperty.manufacturedHomeLandInterest so field 89 never asserts that
  // the security includes land without a recorded ownership interest, and the
  // contradictory pair (89 = 1, 90 = 5) is never emitted.
  const manufacturedHome = manufacturedHomeCodes(
    manufactured,
    str(subjectProperty?.manufacturedHomeLandInterest),
  );
  const unitsByType: Record<string, number> = { "two-unit": 2, "three-unit": 3, "four-unit": 4 };
  const totalUnits = num(subjectProperty?.numberOfUnits) ?? unitsByType[propertyType ?? ""] ?? 1;

  // --- Census tract / county (stored task-015 geocode) -------------------
  const censusTractRaw = str(geocode?.censusTract);
  const censusTractDigits = censusTractRaw ? censusTractRaw.replace(/[^0-9]/g, "") : null;
  const county = censusTractDigits && censusTractDigits.length >= 5 ? censusTractDigits.slice(0, 5) : null;

  // --- Ages at APPLICATION date (never the export date) -------------------
  const appDateParts = app.submittedAt ? etDateParts(app.submittedAt, cfg.timeZone) : null;
  const ageOf = (row: BorrowerRow | null): number | null => {
    if (!row || !appDateParts) return null;
    const dob = decryptDob(row);
    return dob ? ageAtDate(dob, appDateParts) : null;
  };
  const primaryAge = ageOf(primary);
  const coAge = ageOf(coBorrower);

  // --- Income (shared task-010 enumeration, annualized, thousands) --------
  const qualificationInput = buildQualificationInput(
    borrowers.map((b) => ({ employments: b.employments, otherIncome: b.otherIncome })),
    app.data
      ? {
          realEstateOwned: app.data.realEstateOwned,
          liabilities: app.data.liabilities,
          otherLiabilities: app.data.otherLiabilities,
          subjectProperty: app.data.subjectProperty,
          loan: app.data.loan,
          proposedHousingExpense: app.data.proposedHousingExpense,
        }
      : null,
    avm ? { isStale: avm.isStale, status: "completed", result: avm.result } : null,
  );
  const incomeCentsMonthly = monthlyIncomeCents(qualificationInput);
  const incomeThousands = incomeCentsMonthly > 0 ? Math.round((incomeCentsMonthly / 100) * 12 / 1000) : null;

  // --- Credit score (ASM-003 qualifying score, stored check result) -------
  const creditResult = asObject(credit?.result ?? null);
  const qualifyingScore = num(creditResult?.qualifyingScore) ?? num(creditResult?.middleScore);

  // --- Interest Rate (Q11: par scenario via the existing simulation) -------
  //
  // INV-043 (ASM-005 never-originated premise): the Closing-Disclosure-derived
  // money data points — Total Loan Costs (73), Total Points and Fees (74),
  // Origination Charges (75), Discount Points (76) and Lender Credits (77) —
  // are defined by Reg C §1003.4(a)(17)(i),(18),(19),(20) BY REFERENCE to the
  // Closing Disclosure (12 CFR §1026.38(f)(1),(f)(4),(h)(3)), which is only
  // ever issued for a CONSUMMATED transaction. This system never originates a
  // loan (action taken is only 2/3/4), so no Closing Disclosure exists and
  // those five fields report the specification's "NA" on every row — never a
  // pricing-simulation value and never a literal 0.
  //
  // Interest Rate (78) is NOT Closing-Disclosure-derived: §1003.4(a)(21)
  // reports the rate applicable to the approval, which stays reportable for an
  // approved-but-not-accepted row. Only `parRate` is therefore taken from the
  // simulation; the other par-scenario amounts are deliberately discarded.
  let parRate: number | null = null;
  if (isApprovedNotAccepted) {
    const refinance = asObject(loan?.refinance);
    const pricingInput: PricingInput = {
      loanType: str(loan?.loanType) ?? "conventional",
      amortizationType: str(loan?.amortizationType),
      loanTermMonths: num(loan?.loanTermMonths) ?? 0,
      requestedLoanAmount: num(loan?.requestedLoanAmount) ?? 0,
      qualifyingCreditScore: qualifyingScore,
      ltv: decimalToNumber(app.ltv),
      occupancy: str(subjectProperty?.occupancy),
      propertyType,
      numberOfUnits: num(subjectProperty?.numberOfUnits),
      cashOut:
        str(loan?.loanPurpose) === "refinance-cash-out" ||
        str(refinance?.purposeOfRefinance) === "cash-out",
      monthlyPropertyTaxes: num(proposedHousingExpense?.propertyTaxes),
      monthlyInsurance: num(proposedHousingExpense?.homeownersInsurance),
    };
    try {
      const outcome = simulatePricing(pricingInput);
      if (outcome.kind === "result") {
        const par = outcome.result.scenarios.find((s) => s.name === "par");
        if (par) parRate = par.interestRate ?? null;
      }
      // invalid-response (the $999,999 trigger) -> field 78 stays NA
      // (documented simulation-collision note, INV-037).
    } catch (error) {
      if (!(error instanceof PricingInputError)) throw error;
      // Structurally unusable pricing inputs -> NA.
    }
  }

  // --- Property value (shared LTV denominator basis, ASM-006) -------------
  const avmResult = asObject(avm?.result ?? null);
  const avmValue = avm && !avm.isStale ? num(avmResult?.estimatedValue) : null;
  const statedValue = num(subjectProperty?.estimatedValue);
  const propertyValue =
    avmValue !== null && statedValue !== null
      ? Math.min(avmValue, statedValue)
      : avmValue ?? statedValue;

  // --- Denial reasons -----------------------------------------------------
  const isDenied = action.code === HMDA_ACTION_TAKEN.denied;
  const denialCodes = isDenied
    ? (denial?.denialReasons ?? [])
        .map((r) => HMDA_DENIAL_REASON[r])
        .filter((c): c is string => c !== undefined)
        .slice(0, 4)
    : [];
  const denialFreeForm =
    isDenied && denialCodes.includes("9") && denial?.denialReasonOtherText
      ? sanitizeLarText(denial.denialReasonOtherText)
      : "";
  // INV-043 (c): a Reason for Denial of 9 (Other) with an empty conditional
  // free-form text fails the FFIEC validity edit and rejects the ENTIRE
  // submission, not just the row. Refuse to emit it — same posture as the
  // field-count guards above. VR-088 already enforces this on the API
  // boundary; this is the export-side backstop for rows written any other way.
  if (denialCodes.includes("9") && denialFreeForm === "") {
    throw new Error(
      `LAR record for ${app.applicationNumber} would emit Reason for Denial = 9 (Other) ` +
        `with an empty Reason for Denial: Free Form Text (field 72). The FFIEC validity ` +
        `edit rejects the whole submission on that pair (INV-043(c) / VR-088) — repair the ` +
        `deciding deny ApprovalRecord's denialReasonOtherText before exporting.`,
    );
  }

  // --- Demographics -------------------------------------------------------
  const eth1 = ethnicityFields(primaryDemo, false, primary !== null);
  const eth2 = ethnicityFields(coDemo, true, coBorrower !== null);
  const race1 = raceFields(primaryDemo, false, primary !== null);
  const race2 = raceFields(coDemo, true, coBorrower !== null);
  const sex1 = sexFields(primaryDemo, false, primary !== null);
  const sex2 = sexFields(coDemo, true, coBorrower !== null);

  // --- AUS ----------------------------------------------------------------
  const ausResult = asObject(aus?.result ?? null);
  const ausRecommendation = str(ausResult?.recommendation);
  const hasAus = aus !== null;
  const ausSystem1 = hasAus ? "5" : "6";
  const ausFreeForm = hasAus ? "Internal rule-based AUS simulation" : "";
  // The membership guard is what keeps the lookup honest: HMDA_AUS_RESULT is
  // keyed by the AusRecommendation enum, so an unexpected literal falls to the
  // spec's 17 (Not applicable) rather than silently indexing with `any`.
  const ausResult1 =
    hasAus && ausRecommendation !== null && ausRecommendation in HMDA_AUS_RESULT
      ? HMDA_AUS_RESULT[ausRecommendation as AusRecommendation]
      : "17";

  // --- ARM introductory period -------------------------------------------
  const introRatePeriod =
    str(loan?.amortizationType) === "adjustable" ? num(loan?.armInitialFixedMonths) : null;

  const na = (value: number | null): string => (value === null ? "NA" : String(value));
  const loanAmount = num(loan?.requestedLoanAmount);

  return [
    /*   1 */ "2",
    /*   2 */ cfg.lei,
    /*   3 */ buildUli(cfg.lei, app.applicationNumber),
    /*   4 */ larDate(app.submittedAt, cfg.timeZone),
    /*   5 */ HMDA_LOAN_TYPE[str(loan?.loanType) ?? ""] ?? "1",
    /*   6 */ HMDA_LOAN_PURPOSE[str(loan?.loanPurpose) ?? ""] ?? "5",
    /*   7 */ "2",
    /*   8 */ constructionMethod,
    /*   9 */ HMDA_OCCUPANCY[str(subjectProperty?.occupancy) ?? ""] ?? "1",
    /*  10 */ na(loanAmount),
    /*  11 */ action.code,
    /*  12 */ larDate(action.date, cfg.timeZone),
    /*  13 */ address ? sanitizeLarText([str(address.street), str(address.unit)].filter(Boolean).join(" ")) || "NA" : "NA",
    /*  14 */ address && str(address.city) ? sanitizeLarText(str(address.city)!) : "NA",
    /*  15 */ str(address?.state) ?? "NA",
    /*  16 */ address && str(address.zip) ? sanitizeLarText(str(address.zip)!) : "NA",
    /*  17 */ county ?? "NA",
    /*  18 */ censusTractDigits ?? "NA",
    /*  19 */ eth1.codes[0],
    /*  20 */ eth1.codes[1],
    /*  21 */ eth1.codes[2],
    /*  22 */ eth1.codes[3],
    /*  23 */ eth1.codes[4],
    /*  24 */ eth1.freeForm,
    /*  25 */ eth2.codes[0],
    /*  26 */ eth2.codes[1],
    /*  27 */ eth2.codes[2],
    /*  28 */ eth2.codes[3],
    /*  29 */ eth2.codes[4],
    /*  30 */ eth2.freeForm,
    /*  31 */ eth1.visualObservation,
    /*  32 */ eth2.visualObservation,
    /*  33 */ race1.codes[0],
    /*  34 */ race1.codes[1],
    /*  35 */ race1.codes[2],
    /*  36 */ race1.codes[3],
    /*  37 */ race1.codes[4],
    /*  38 */ race1.tribeFreeForm,
    /*  39 */ race1.otherAsianFreeForm,
    /*  40 */ race1.otherPacificFreeForm,
    /*  41 */ race2.codes[0],
    /*  42 */ race2.codes[1],
    /*  43 */ race2.codes[2],
    /*  44 */ race2.codes[3],
    /*  45 */ race2.codes[4],
    /*  46 */ race2.tribeFreeForm,
    /*  47 */ race2.otherAsianFreeForm,
    /*  48 */ race2.otherPacificFreeForm,
    /*  49 */ race1.visualObservation,
    /*  50 */ race2.visualObservation,
    /*  51 */ sex1.code,
    /*  52 */ sex2.code,
    /*  53 */ sex1.visualObservation,
    /*  54 */ sex2.visualObservation,
    /*  55 */ primaryAge !== null ? String(primaryAge) : "8888",
    /*  56 */ coBorrower === null ? NO_CO_APPLICANT.age : coAge !== null ? String(coAge) : "8888",
    /*  57 */ incomeThousands !== null ? String(incomeThousands) : "NA",
    /*  58 */ "0",
    /*  59 */ "NA",
    /*  60 */ "3",
    /*  61 */ "1",
    /*  62 */ qualifyingScore !== null ? String(qualifyingScore) : "8888",
    /*  63 */ coBorrower === null ? NO_CO_APPLICANT.creditScore : "8888",
    /*  64 */ qualifyingScore !== null ? "8" : "9",
    /*  65 */ qualifyingScore !== null ? "Simulated tri-bureau middle score" : "",
    /*  66 */ coBorrower === null ? NO_CO_APPLICANT.creditScoreModel : "9",
    /*  67 */ "",
    /*  68 */ isDenied ? denialCodes[0] ?? "10" : "10",
    /*  69 */ denialCodes[1] ?? "",
    /*  70 */ denialCodes[2] ?? "",
    /*  71 */ denialCodes[3] ?? "",
    /*  72 */ denialFreeForm,
    /*  73 */ "NA", // INV-043: Closing-Disclosure-derived, never issued
    /*  74 */ "NA",
    /*  75 */ "NA", // INV-043
    /*  76 */ "NA", // INV-043 (never a literal 0)
    /*  77 */ "NA", // INV-043 (never a literal 0)
    /*  78 */ na(parRate),
    /*  79 */ "NA",
    /*  80 */ na(decimalToNumber(app.dti)),
    /*  81 */ na(decimalToNumber(app.cltv)),
    /*  82 */ na(num(loan?.loanTermMonths)),
    /*  83 */ na(introRatePeriod),
    /*  84 */ "2",
    /*  85 */ "2",
    /*  86 */ "2",
    /*  87 */ "2",
    /*  88 */ na(propertyValue),
    /*  89 */ manufacturedHome.securedPropertyType,
    /*  90 */ manufacturedHome.landPropertyInterest,
    /*  91 */ String(totalUnits),
    /*  92 */ "NA",
    /*  93 */ "1",
    /*  94 */ "1", // INV-043 (b): §1003.4(a)(34) extends to applications
    /*  95 */ "NA",
    /*  96 */ ausSystem1,
    /*  97 */ "",
    /*  98 */ "",
    /*  99 */ "",
    /* 100 */ "",
    /* 101 */ ausFreeForm,
    /* 102 */ ausResult1,
    /* 103 */ "",
    /* 104 */ "",
    /* 105 */ "",
    /* 106 */ "",
    /* 107 */ "",
    /* 108 */ "2",
    /* 109 */ "2",
    /* 110 */ "2",
  ];
}

// ---------------------------------------------------------------------------
// Route body helper
// ---------------------------------------------------------------------------

/** UTF-8 byte stream of the LAR file (route Response body — SEC-14 streamed). */
export function larByteStream(
  year: number,
  cfg: HmdaLarConfig,
  db: PrismaClient = prisma,
): ReadableStream<Uint8Array> {
  const encoder = new TextEncoder();
  const lines = generateLarFile(year, cfg, db);
  const iterator = lines[Symbol.asyncIterator]();
  return new ReadableStream<Uint8Array>({
    async pull(controller) {
      const { value, done } = await iterator.next();
      if (done) {
        controller.close();
        return;
      }
      controller.enqueue(encoder.encode(value));
    },
    async cancel() {
      await iterator.return?.(undefined);
    },
  });
}
